name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 5
      matrix:
        image:
          - almalinux_8_appstream_1.16
          - almalinux_8_appstream_1.18
          - almalinux_8_appstream_1.20
          - almalinux_8_appstream_1.22
          - almalinux_8_epel-modular_mainline
          - almalinux_9
          - almalinux_9_appstream_1.22
        arch:
          - linux/amd64
          - linux/arm64/v8

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build RPM
        run: |
          ./build -p ${{ matrix.arch }} $(echo ${BUILD_IMAGE} | sed 's/_/:/g')

      - name: Normalize artifact name
        run: echo "ARTIFACT_NAME=$(echo ${{ matrix.image }}-${{ matrix.arch }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: rpmbuild/**/*.rpm
